language: cpp
dist: xenial

matrix:
  include:
    - name: Linux
      addons:
        apt_packages:
          - cmake
          - libxrandr-dev
          - libudev-dev
          - libopenal-dev
          - libflac-dev
          - libvorbis-dev
          - libgl1-mesa-dev
          - unzip
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update -q
        - sudo apt-get install g++-8 -y
      before_script:
        - wget "https://github.com/SFML/SFML/releases/download/2.5.1/SFML-2.5.1-sources.zip" && unzip SFML-2.5.1-sources.zip && cd SFML-2.5.1 && mkdir build && cd build &&
          cmake .. $CMAKE_FLAGS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install
        - cmake --build . --config Release --target install
        - cd ../..
        - wget "https://github.com/ocornut/imgui/archive/v1.73.zip" && unzip v1.73.zip
        - wget "https://github.com/eliasdaler/imgui-sfml/archive/v2.1.zip" && unzip v2.1.zip && cd imgui-sfml-2.1 && mkdir build && cd build &&
          cmake .. $CMAKE_FLAGS -DCMAKE_INSTALL_PREFIX=../install -DIMGUI_DIR=$TRAVIS_BUILD_DIR/imgui-1.73 -DSFML_DIR=$TRAVIS_BUILD_DIR/SFML-2.5.1/install/lib/cmake/SFML -DBUILD_SHARED_LIBS=ON
        - cmake --build . --config Release --target install
        - cd ../..
      script:
        - export CC=gcc-8
        - export CXX=g++-8
        - mkdir build && cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS -DSFML_DIR=$TRAVIS_BUILD_DIR/SFML-2.5.1/install/lib/cmake/SFML -DImGui-SFML_DIR=$TRAVIS_BUILD_DIR/imgui-sfml-2.1/install/lib/cmake/ImGui-SFML -DCMAKE_INSTALL_PREFIX=../install
        - cmake --build . --config Release
    - name: macOS
      compiler: clang
      os: osx
      osx_image: xcode10.2
      before_script:
        - brew install sfml
        - wget "https://github.com/ocornut/imgui/archive/v1.73.zip" && unzip v1.73.zip
        - git clone https://github.com/eliasdaler/imgui-sfml.git
        - cd imgui-sfml && mkdir build && cd build &&
          cmake .. $CMAKE_FLAGS -DCMAKE_INSTALL_PREFIX=../install -DIMGUI_DIR=$TRAVIS_BUILD_DIR/imgui-1.73 -DBUILD_SHARED_LIBS=ON
        - cmake --build . --config Release --target install
        - cd ../..
      script:
        - mkdir build && cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS -DImGui-SFML_DIR=$TRAVIS_BUILD_DIR/imgui-sfml/install/lib/cmake/ImGui-SFML -DCMAKE_INSTALL_PREFIX=../install
        - cmake --build . --config Release
