{
  "language": "cpp",
  "os": [
    "linux"
  ],
  "dist": "bionic",
  "deploy": [
  {
    "provider": "releases",
    "file_glob": true,
    "file": [
      "engge-*.zip"
    ],
    "skip_cleanup": true,
    "on": {
      "tags": true
    },
    "tag_name": "$TRAVIS_TAG",
    "name": "$TRAVIS_COMMIT_MESSAGE",
    "draft": true,
    "token": {
      "secure": "YzN2W7SkV2T5cO/st5e/RwiRuMSkoyyzsBwii6K3Mvmybu6KM/FpLAMs7fCGxqjj/EAHbUFBNW6mJC9xlqRC5ee24x1B8KhRM2FEbTz9oUPnFnGJJK+8SKqVtnLhXdEdfC1adcL0TrJsaP9kiudgbwGNOXHzddNwfpciMhKanNmc9N+c0eHhlIbpVIGBaYDUf960ON7NKwMsYgUyWm72Z2mchUAY43Q44QOB+TZ1dn0alCsvaBzGRqHXNcq8jLhFYiltilUP85g90ebe2lwEgVsCjjU1DkorQr3oTlcONHXB5O+i0SJUjpHxGDNUxcmgf5rKnyHlHZfKITQwNN5rxHMHiPX1LQuTlTx0WDc+sXloAVpj/ZV7ubIlOjKjXL530CcLISCi4DothjRLeXzXEIEa14GcrmQRHIU0scukp7kmP2PhqQhYCcjzKZcFdD8f6YvrCWcnQydXwy4/1HZBvg40gMtS11va29hn0YuvK3SnYyjVG6un7RBryfIArzdZYv5rriOU5HlFekdYaMWgcVz335283a3kkv8YpBhLPB/DUhy2wni2znObDur5dxDdjulRe6tOyTmWPfYO/v3hqE2haH0GcULJHhA9RodRiGrG+fQIzoYlAkQWSGAMWWf9MXqz+WDH1hUKSKt6m+QpjgmVOiQpOrJIFeX+YZDK5qQ="
    }
  }
  ],
  "jobs": {
    "include": [
    {
      "name": "Linux",
      "addons": {
        "apt": {
          "packages": [
            "cmake",
            "libxrandr-dev",
            "libudev-dev",
            "libopenal-dev",
            "libflac-dev",
            "libvorbis-dev",
            "libgl1-mesa-dev",
            "unzip"
          ]
        }
      },
      "before_install": [
        "sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y",
        "sudo apt-get update -q",
        "sudo apt-get install g++-8 patchelf -y"
      ],
      "before_script": [
        "wget \"https://github.com/SFML/SFML/releases/download/2.5.1/SFML-2.5.1-sources.zip\" && unzip SFML-2.5.1-sources.zip && cd SFML-2.5.1 && mkdir build && cd build && cmake .. $CMAKE_FLAGS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install",
        "cmake --build . --config Release --target install",
        "cd ../..",
        "wget \"https://github.com/ocornut/imgui/archive/v1.73.zip\" && unzip v1.73.zip",
        "wget \"https://github.com/eliasdaler/imgui-sfml/archive/v2.1.zip\" && unzip v2.1.zip && cd imgui-sfml-2.1 && mkdir build && cd build && cmake .. $CMAKE_FLAGS -DCMAKE_INSTALL_PREFIX=../install -DIMGUI_DIR=$TRAVIS_BUILD_DIR/imgui-1.73 -DSFML_DIR=$TRAVIS_BUILD_DIR/SFML-2.5.1/install/lib/cmake/SFML -DBUILD_SHARED_LIBS=ON",
        "cmake --build . --config Release --target install",
        "cd ../.."
      ],
      "script": [
        "export CC=gcc-8",
        "export CXX=g++-8",
        "mkdir build && cd build",
        "cmake .. -DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS -DSFML_DIR=$TRAVIS_BUILD_DIR/SFML-2.5.1/install/lib/cmake/SFML -DImGui-SFML_DIR=$TRAVIS_BUILD_DIR/imgui-sfml-2.1/install/lib/cmake/ImGui-SFML -DCMAKE_INSTALL_PREFIX=../install",
        "cmake --build . --config Release --target package"
      ]
    },
    {
      "name": "macOS",
      "compiler": "clang",
      "os": "osx",
      "osx_image": "xcode11",
      "before_script": [
        "brew install sfml",
        "wget \"https://github.com/ocornut/imgui/archive/v1.73.zip\" && unzip v1.73.zip",
        "git clone https://github.com/eliasdaler/imgui-sfml.git",
        "cd imgui-sfml && mkdir build && cd build && cmake .. $CMAKE_FLAGS -DCMAKE_INSTALL_PREFIX=../install -DIMGUI_DIR=$TRAVIS_BUILD_DIR/imgui-1.73 -DBUILD_SHARED_LIBS=ON",
        "cmake --build . --config Release --target install",
        "cd ../.."
      ],
      "script": [
        "mkdir build && cd build",
        "cmake .. -DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS -DImGui-SFML_DIR=$TRAVIS_BUILD_DIR/imgui-sfml/install/lib/cmake/ImGui-SFML -DCMAKE_INSTALL_PREFIX=../install",
        "cmake --build . --config Release --target package"
      ]
    }
    ]
  }
}