image: Visual Studio 2017

platform: x64

environment:
  MSVC_DEFAULT_OPTIONS: ON
  SFML_DIR: C:\Libraries\SFML-2.5.1
  IMGUI_DIR: C:\Libraries\imgui-1.73
  IMGUI_SFML_DIR: C:\Libraries\imgui-sfml-2.1
  
configuration: Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version
  
build_script:
  - ps: echo $env:SFML_DIR
  - ps: echo $env:IMGUI_DIR
  - ps: echo $env:IMGUI_SFML_DIR
  - ps: cd C:\Libraries
  - ps: Start-FileDownload "https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc15-64-bit.zip"
  - ps: 7z.exe x SFML-2.5.1-windows-vc15-64-bit.zip
  - ps: Start-FileDownload "https://github.com/ocornut/imgui/archive/v1.73.zip"
  - ps: 7z.exe x v1.73.zip
  - ps: dir C:\Libraries
  - ps: dir "$env:IMGUI_DIR"
  - ps: Start-FileDownload "https://github.com/eliasdaler/imgui-sfml/archive/v2.1.zip"
  - ps: 7z.exe x v2.1.zip
  - ps: dir C:\Libraries
  - ps: dir "$env:IMGUI_SFML_DIR"
  - ps: cd "$env:IMGUI_SFML_DIR"
  - ps: mkdir build
  - ps: mkdir install
  - ps: cd "$env:IMGUI_SFML_DIR\build"
  - ps: cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=../install -DIMGUI_DIR="$env:IMGUI_DIR" -DSFML_DIR=$env:SFML_DIR -DBUILD_SHARED_LIBS=ON
  - ps: cmake --build . --config Release --target install
  - ps: dir "$env:IMGUI_SFML_DIR\install"
  - ps: cd C:\projects\engge
  - ps: mkdir build
  - ps: mkdir install
  - ps: cd build
  - ps: cmake .. -G "Visual Studio 15 2017 Win64" -DSFML_DIR=$env:SFML_DIR -DImGui-SFML_DIR="/lib/cmake/ImGui-SFML" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install
  - ps: cmake --build . --config Release --target package
  - ps: cd "$env:APPVEYOR_BUILD_FOLDER"
    
artifacts:
  - path: build\engge-*.zip

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: 4Fs9Shs13/CwcIHJDQAm+kNRZzsTSxsBi07gSfFHqK17nhlfwRGSYMA56XpRzeMM
    repository: scemino/engge
    artifact: /.*\.zip/
    draft: true
    prerelease: true
    on:
      appveyor_repo_tag: true